### PR TITLE
sheduler

### PR DESCRIPTION
**Pull request by lexsysko**
`sheduler.py -h`
```          
usage: sheduler.py [-h] [--loop] [--delay DELAY] [-t TELEGRAM_PERIOD] [-l LIMIT_PERIOD]

Infinite loop of service app events

options:
  -h, --help            show this help message and exit
  --loop
  --delay DELAY         loop delay in seconds, default 1 sec
  -t TELEGRAM_PERIOD, --telegram_period TELEGRAM_PERIOD
                        Telegram bot pool period in seconds, default 2 sec
  -l LIMIT_PERIOD, --limit_period LIMIT_PERIOD
                        Limit Check period in seconds, default 300 sec
                        
```

`sheduler.py" --loop -l 15`
```
Loop... 1
Loop... 1
- handler_telegram_pool
last_update_id=286860364
Loop... 1
Loop... 1
- handler_telegram_pool
last_update_id=286860364
Loop... 1
Loop... 1
- handler_telegram_pool
last_update_id=286860364
Loop... 1
Loop... 1
- handler_telegram_pool
last_update_id=286860364
Loop... 1
Loop... 1
- handler_telegram_pool
last_update_id=286860364
Loop... 1
Loop... 1
- handler_telegram_pool
last_update_id=286860364
- handler_limit_check
Loop... 1
Loop... 1
- handler_telegram_pool
last_update_id=286860364
Loop... 1
Loop... 1
*** Terminated by user pressing: Ctrl-C
```

image

### CODE REVIEW

**Comment by artem-dorofeev** [comment]
ok

**Comment by artem-dorofeev** [comment]
ok

**Comment by lexsysko** [comment]
> ok

А appove ?

**Review by artem-dorofeev — APPROVED** [review]
ok

**Pull request merged**
